name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Show CLI help
        run: python app.py -h || true

      - name: Ruff (lint)
        run: ruff check .
